name: MySQL CI Example2

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
    steps:
      - uses: actions/checkout@v4
      - name: Wait for MySQL
        run: |
          # Simple wait for MySQL to be ready (more robust solutions exist)
          sleep 10
      - name: Execute SQL script
        run: |
          mysql -h 127.0.0.1 -P 3306 -uroot -proot_password test_db < schema.sql
          # Here you would typically run your application's tests against this DB
      - name: Run application tests
        run: mysql -h 127.0.0.1 -P 3306 -uroot -proot_password test_db < data.sql
          # Your application's test commands that connect to the MySQL service
         
